<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Install Reklamepedia CMS</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',sans-serif;background:#0f1012;color:#e5e7eb;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}
.card{background:#1a1c1e;border:1px solid #2a2d30;border-radius:16px;padding:40px;max-width:560px;width:100%}
h1{font-size:24px;font-weight:700;margin-bottom:8px;color:#fff}
p{color:#9ca3af;margin-bottom:24px;font-size:14px}
.step{background:#111315;border:1px solid #2a2d30;border-radius:10px;padding:16px;margin-bottom:12px}
.step-title{font-weight:600;margin-bottom:4px}
.step-desc{font-size:13px;color:#6b7280}
label{display:block;font-size:13px;color:#9ca3af;margin-bottom:6px;margin-top:16px}
input{width:100%;background:#111315;border:1px solid #374151;border-radius:8px;padding:10px 14px;color:#e5e7eb;font-size:14px;outline:none}
input:focus{border-color:#e8a020}
.btn{display:block;width:100%;padding:14px;background:#e8a020;color:#000;border:none;border-radius:10px;font-size:15px;font-weight:700;cursor:pointer;margin-top:24px}
.btn:hover{background:#d4911a}
.alert{padding:14px;border-radius:10px;margin-bottom:16px;font-size:14px}
.alert-error{background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.3);color:#f87171}
.alert-success{background:rgba(74,222,128,.1);border:1px solid rgba(74,222,128,.3);color:#4ade80}
.logo{font-size:32px;margin-bottom:16px}
code{background:#111315;padding:2px 8px;border-radius:4px;font-size:12px;color:#e8a020}
</style>
</head>
<body>
<?php
$step = (int)($_POST['step'] ?? $_GET['step'] ?? 1);
$errors = [];
$success = '';

// Step 2: Test DB connection & install
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $db_host = trim($_POST['db_host'] ?? 'localhost');
    $db_name = trim($_POST['db_name'] ?? '');
    $db_user = trim($_POST['db_user'] ?? '');
    $db_pass = $_POST['db_pass'] ?? '';
    $db_port = (int)($_POST['db_port'] ?? 3306);

    if (!$db_name) $errors[] = 'Nama database wajib diisi.';
    if (!$db_user) $errors[] = 'Username database wajib diisi.';

    if (empty($errors)) {
        try {
            $dsn = "mysql:host=$db_host;port=$db_port;dbname=$db_name;charset=utf8mb4";
            $pdo = new PDO($dsn, $db_user, $db_pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

            // Run schema
            $sql = file_get_contents(__DIR__ . '/database.sql');
            // Split by statement
            $statements = array_filter(array_map('trim', explode(";\n", $sql)));
            foreach ($statements as $stmt) {
                if (trim($stmt)) $pdo->exec($stmt);
            }

            // Write config
            $config_content = <<<CONFIG
<?php
// AUTO-GENERATED BY INSTALLER
// Generated: <?= date('Y-m-d H:i:s') ?>

define('DB_HOST', '$db_host');
define('DB_PORT', $db_port);
define('DB_NAME', '$db_name');
define('DB_USER', '$db_user');
define('DB_PASS', '$db_pass');
define('DB_CHARSET', 'utf8mb4');

define('BASE_URL', (isset(\$_SERVER['HTTPS']) ? 'https' : 'http') . '://' . \$_SERVER['HTTP_HOST'] . rtrim(dirname(\$_SERVER['SCRIPT_NAME']), '/install.php'));
define('UPLOADS_PATH', __DIR__ . '/../uploads');
define('UPLOADS_URL', BASE_URL . '/uploads');
define('THEMES_PATH', __DIR__ . '/../themes');
CONFIG;

            file_put_contents(__DIR__ . '/core/config/db.php', $config_content);

            // Create uploads dir
            $dirs = ['uploads','uploads/produk','uploads/gallery','uploads/blog','uploads/layanan','uploads/settings','uploads/avatars','uploads/slides'];
            foreach ($dirs as $dir) {
                if (!is_dir(__DIR__.'/'.$dir)) mkdir(__DIR__.'/'.$dir, 0755, true);
            }

            $step = 3;
            $success = 'Instalasi berhasil! Database sudah terkonfigurasi.';
        } catch (PDOException $e) {
            $errors[] = 'Koneksi gagal: ' . $e->getMessage();
        }
    }
}
?>

<div class="card">
    <div class="logo">🎨</div>
    <h1>Reklamepedia CMS Installer</h1>
    <p>Setup awal untuk menginstal Reklamepedia CMS di server Anda.</p>

    <?php if (!empty($errors)): foreach ($errors as $e): ?>
    <div class="alert alert-error">⚠️ <?= htmlspecialchars($e) ?></div>
    <?php endforeach; endif; ?>

    <?php if ($success): ?>
    <div class="alert alert-success">✅ <?= htmlspecialchars($success) ?></div>
    <?php endif; ?>

    <?php if ($step === 1): ?>
    <!-- Step 1: Check Requirements -->
    <div style="margin-bottom:24px">
        <?php
        $checks = [
            ['PHP >= 8.0', PHP_VERSION_ID >= 80000, PHP_VERSION],
            ['PDO MySQL', extension_loaded('pdo_mysql'), null],
            ['GD / Image', extension_loaded('gd'), null],
            ['Fileinfo', extension_loaded('fileinfo'), null],
            ['Writable /core/config', is_writable(__DIR__.'/core/config'), null],
            ['Writable /uploads (or creatable)', is_writable(__DIR__) || is_dir(__DIR__.'/uploads'), null],
        ];
        $all_ok = true;
        foreach ($checks as [$label, $ok, $extra]):
            if (!$ok) $all_ok = false;
        ?>
        <div class="step">
            <div style="display:flex;align-items:center;gap:10px">
                <span style="font-size:20px"><?= $ok ? '✅' : '❌' ?></span>
                <div>
                    <div class="step-title"><?= $label ?></div>
                    <?php if ($extra): ?><div class="step-desc"><?= htmlspecialchars($extra) ?></div><?php endif; ?>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>

    <?php if ($all_ok): ?>
    <form method="GET">
        <input type="hidden" name="step" value="2">
        <button type="submit" class="btn">Lanjutkan ke Konfigurasi Database →</button>
    </form>
    <?php else: ?>
    <div class="alert alert-error">Perbaiki persyaratan di atas sebelum melanjutkan.</div>
    <?php endif; ?>

    <?php elseif ($step === 2): ?>
    <!-- Step 2: Database Config -->
    <form method="POST">
        <input type="hidden" name="step" value="2">
        <label>Database Host</label>
        <input type="text" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>">
        <label>Port</label>
        <input type="text" name="db_port" value="<?= htmlspecialchars($_POST['db_port'] ?? '3306') ?>">
        <label>Nama Database</label>
        <input type="text" name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? 'reklamepedia_cms') ?>" required>
        <label>Username Database</label>
        <input type="text" name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? 'root') ?>" required>
        <label>Password Database</label>
        <input type="password" name="db_pass" value="">
        <button type="submit" class="btn">🚀 Install Database</button>
    </form>

    <?php elseif ($step === 3): ?>
    <!-- Step 3: Done -->
    <div style="text-align:center;padding:20px 0">
        <div style="font-size:64px;margin-bottom:16px">🎉</div>
        <h2 style="font-size:20px;color:#fff;margin-bottom:12px">Instalasi Selesai!</h2>
        <p style="margin-bottom:24px">Reklamepedia CMS berhasil diinstal. Hapus file <code>install.php</code> dari server setelah ini.</p>
        <div class="step" style="text-align:left;margin-bottom:16px">
            <div class="step-title">🔑 Kredensial Admin Default</div>
            <div class="step-desc" style="margin-top:8px">
                URL Admin: <code>/admin/</code><br>
                Username: <code>admin</code><br>
                Password: <code>Admin@123</code><br><br>
                <strong style="color:#f87171">⚠️ Segera ganti password di Setup Wizard!</strong>
            </div>
        </div>
        <a href="admin/" style="display:inline-block;padding:14px 32px;background:#e8a020;color:#000;text-decoration:none;border-radius:10px;font-weight:700">
            Buka Admin Panel →
        </a>
    </div>
    <?php endif; ?>
</div>
</body>
</html>
